version: '3.8'
services:
  app:
    container_name: ${API_NAME}-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    command: npm run dev
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
